export const Users = [
  {
    id: 1,
    profilePicture: "/assets/img/1.jpg",
    username: "Pradeep Das",
  },
  {
    id: 2,
    profilePicture: "/assets/img/2.jpg",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "/assets/img/3.jpg",
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: "/assets/img/4.jpg",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "/assets/img/5.jpg",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "/assets/img/6.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: "/assets/img/7.jpg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "/assets/img/8.jpg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "/assets/img/9.jpg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "/assets/img/10.jpg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: " God is Almighty",
    photo: "/assets/img/1.jpg",
    date: "50 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/assets/img/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Never give up, Giving up is disrespect to the god",
    photo: "/assets/img/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/assets/img/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/assets/img/cover.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/assets/img/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/assets/img/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/assets/img/new2.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "/assets/img/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/assets/img/new1.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
